spring:
  data:
    mongodb:
      host: mongo
      username: msApp
      paswword: '{cipher}30d058864c5b032d31ca6c5d008fcdc38073d6a707d8f7ebd7c3ad8f1e9e2a50'
welcome:
  message: "Welcome to default version"